### ISSUE TITLE
Being able to check if a message (request/response) is a CON ?

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#29]
Following #27, I created this issue.

The need : 
> is there a way to check if a message (request or response) is CON or not ? something like :` if (!CON.equals(coapRequest.getType()))`

A possible way :
> At the moment there is no way to check it if incoming request or response was NON. If needed this info can be easily added to `TransportContext`

**Comment by szysas** [comment]
@sbernard31 It is possible to check if request was NON from context, for example:
```
req.getTransContext().get(NON_CONFIRMABLE)
```

Similarly, request can be force to be NON by setting context, for example:
```
post(LOCAL_5683, "/test2").token(13).payload("test").context(NON_CONFIRMABLE, true)
```

Can we close this ticket?

**Comment by sbernard31** [comment]
Just to be sure, what I need to do is to ensure that a request is a CON. 
I guess the right way to do that is :  
```java
if (coapRequest.getTransContext().get(TransportContext.NON_CONFIRMABLE)) {
   // raise an error;
}
```
I guess this is OK as a request is either a CON or a NON, right ?

**Comment by szysas** [comment]
Yes, that will work.

**Comment by sbernard31** [comment]
So let's close this issue, thx for the addition :pray:
