### ISSUE TITLE
Add support of Option without value in Uri-Query.

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#45]
`coapRequest.options().getUriQueryMap()` seems to only support Option  in the form of a "key=value" pair. 
It should also support more simple form like "key" without value. 

(See more detailed at :  https://github.com/open-coap/java-coap/issues/27#issuecomment-1507287371)

**Comment by szysas** [comment]
Currently empty query value can be placed in such way: `field1=value1&field2=&field3=`, so equal sign is needed. Would that work with Leshan?

**Comment by sbernard31** [comment]
Nope that does not match the LWM2M specification :grimacing: 

See for Q option : 
/rd?ep={Endpoint Client Name}&lt={Lifetime}&lwm2m={version}&b={binding}**&Q**&sms={MSISDN}

**Comment by sbernard31** [comment]
Currently I parse UriQuery by myself using : 

```java
public class QueryUtil {
    public static Map<String, String> parseUriQuery(String uriQuery) {
        if (uriQuery == null || uriQuery.length() == 0) {
            return Collections.emptyMap();
        }
        Map<String, String> result = new LinkedHashMap<>();
        String[] params = uriQuery.substring(uriQuery.indexOf('?') + 1).split("&");

        for (String prm : params) {
            String[] p = prm.split("=", 2);
            if (p.length == 2) {
                result.put(p[0], p[1]);
            } else if (p.length == 1) {
                result.put(p[0], null);
            } else {
                throw new IllegalArgumentException();
            }
        }
        return result;
    }
}
```

```java
for (Entry<String, String> entry : QueryUtil.parseUriQuery(coapRequest.options().getUriQuery())
                    .entrySet()) {
 ... .. 
}
```

**Comment by szysas** [comment]
There is release v6.12.0 that contains implementation for this ticket, can we close it?

**Comment by sbernard31** [comment]
Tested with v6.12.0, my integrations tests pass now without my "HACK" :heavy_check_mark: 

Thx for adding this :pray:
