### ISSUE TITLE
Using Semantic Versioning to manage API changes ?

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#53]
This issue aims to discuss about how to manage API changes in the future (not a short term question): 
- should [Semantic Versioning](https://semver.org/)) be used ? Or anything else ?
- which tooling can be used ?

This was triggered by https://github.com/open-coap/java-coap/issues/48#issuecomment-1531502562: 
>>  Not the first time when I update java-coap there is API break between 2 minor version, for now this is not a problem as we are in development phase, but if we release a stable version of Leshan including java-coap dependency, that could be an issue. Did you already consider to maybe move to [Semantic Versioning](https://semver.org/) ?
>
> Yes, I am aware of that. When needed, we can switch to be more strict with API changes.

**Comment by sbernard31** [comment]
About tooling, it exist this maven plugin : https://revapi.org/revapi-site/main/index.html

**Comment by szysas** [comment]
Closing this for now, in this project we need to be able to do fast and small changes and treat every commit to main branch as production ready.

**Comment by sbernard31** [comment]
> When needed, we can switch to be more strict with API changes.

Just for clarify, does it mean that :point_up:  is still true ? or that means :point_up: is no more goal for the future  ?

**Comment by szysas** [comment]
Yes, it is true, when needed, we can switch to be more strict with API changes.
