### ISSUE TITLE
New CoapRequest / CoapResponse Builder API feedback

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#73]
I updated **Leshan** code to use the new **java-coap** API. 

I think the API is largely better now :+1:

Only issue I faced was when I wanted to modify a `CoapRequest` to add element in `TransportContext`.

I didn't find better way than : 
```java
TransportContext extendedContext = observeRequest.getTransContext() //
                            .with(LwM2mKeys.LESHAN_OBSERVED_PATHS, paths);

CoapRequest modifiedObservedRequest = new CoapRequest(observeRequest.getMethod(),
        observeRequest.getToken(), observeRequest.options(), observeRequest.getPayload(),
        observeRequest.getPeerAddress(), extendedContext);

super.add(modifiedObservedRequest);
```

A solution to avoid the verbose `coapRequest` creation could be https://github.com/open-coap/java-coap/pull/68#discussion_r1344358349  and so here this could look like : 
```java
TransportContext extendedContext = observeRequest.getTransContext() //
                            .with(LwM2mKeys.LESHAN_OBSERVED_PATHS, paths);

super.add(coapRequest.modify().context(extendedContext).build());
```

Maybe we could also add a method to modify transportContext in the builder ? something like : 
```java 
super.add(coapRequest.modify()
                     .context(ctx -> ctx.with(LwM2mKeys.LESHAN_OBSERVED_PATHS, paths))
                     .build());
```

Note that: 
 - those new methods can be added without deprecating    `with*(...)` methods a first time. (if you think this is too soon)
 - `modify()` method probably also makes sense for `CoapResponse`

(If you are curious the whole migration change are available at : https://github.com/eclipse-leshan/leshan/commit/c2f823244de882f4ad682c99928e0b78f57c2133)

**Comment by szysas** [comment]
Thanks for feedback. I agree than modifying transport context is really needed.
Thanks for spotting outdated readme. It is actually based on theses tests: https://github.com/open-coap/java-coap/blob/master/coap-core/src/test/java/protocolTests/UsageTest.java. Do you know any idea/tools how to verify if readme examples are up to date?

**Comment by sbernard31** [comment]
> Do you know any idea/tools how to verify if readme examples are up to date?

I had some ideas but not sure they really works : 
- I was thinking about using checkstyle with [regexp](https://checkstyle.org/checks/regexp/index.html) ? (but probably not work) 
- Using this github actions ? https://github.com/marketplace/actions/markdown-autodocs 
- Using [another supported language](https://github.com/github/markup#markups) than markdown (e.g. [reStructuredText](https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment) or [asciidoctor](https://docs.asciidoctor.org/asciidoc/latest/directives/include-lines/)) which have include directive but it seems that [github doesn't support it](https://github.com/github/markup/issues/1524) ... 
- Using github code import but I understand you need to create permalink each time ...  (and rendering is not so good)
https://github.com/open-coap/java-coap/blob/fa79e863d661cd91d8145890634e20ecb5e9fbca/coap-core/src/test/java/protocolTests/UsageTest.java#L64-L88

So nothing great :grimacing:

**Comment by szysas** [comment]
> I had some ideas but not sure they really works

Thanks
