### ISSUE TITLE
Missing API in Transport Context

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#82]
Implementing coap(s)+tcp in Leshan, I faced some issues that could be solve with API additions : 
(I found workaround for each of them, so there is no urgency)

**1. A way to iterate over keys of `TransportContext`** 

Maybe a `Collection<Key<?>> getKeys()` methods ? or  make `TransportContext` implements `Iterable` ?

[Here](https://github.com/eclipse-leshan/leshan/blob/170d4095618e1371470ef27c61df5de4885b8610/leshan-tl-javacoap-server-coaptcp/src/main/java/org/eclipse/leshan/transport/javacoap/server/coaptcp/transport/DefaultTransportContextMatcher.java#L29-L57) an example of  usage.

**2. I need to add all keys from a `TransportContext` to an other existing `TransportContext`.** 

Proposed API  : 
 - Adding to `TransportContext`  a method `with(TransportContext contextToMerge)`
 - Adding a  `CoapRequest.Builder` a method `addContext(TransportContext contextToMerge)`

**Comment by szysas** [comment]
Those should be easy ones.. but lets see.
