### ISSUE TITLE
`nonPublicPartOfAPI` for `RawOption` reported by revapi 

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#86]
I'm using [revapi](https://revapi.org), to check I respect semantic versioning in leshan.
But it also checks some code smell about API.
When building leshan,  it report something wrong with java-coap (this is probably not new but before I just ignored all error from java-coap and I changed my build config about that recently)

Report : 
```javascript
{
  "ignore": true,
  "code": "java.class.nonPublicPartOfAPI",
  "new": "class com.mbed.coap.packet.RawOption",
  "justification": "ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE"
   "classSimpleName": "RawOption",
  "exampleUseChainInNewApi": "com.mbed.coap.packet.RawOption is used as a type parameter or type variable bound on method java.util.List<com.mbed.coap.packet.RawOption> com.mbed.coap.packet.HeaderOptions::getRawOptions() <- com.mbed.coap.packet.HeaderOptions is used as a type parameter or type variable bound on method com.mbed.coap.packet.CoapOptionsBuilder com.mbed.coap.packet.CoapOptionsBuilder::ifNull(java.util.function.Function<com.mbed.coap.packet.HeaderOptions, java.lang.Object>, java.util.function.Consumer<com.mbed.coap.packet.CoapOptionsBuilder>) <- com.mbed.coap.packet.CoapOptionsBuilder is used as a type parameter or type variable bound on method com.mbed.coap.packet.CoapResponse.Builder com.mbed.coap.packet.CoapResponse.Builder::options(java.util.function.Consumer<com.mbed.coap.packet.CoapOptionsBuilder>) <- com.mbed.coap.packet.CoapResponse.Builder is returned from method com.mbed.coap.packet.CoapResponse.Builder com.mbed.coap.packet.CoapResponse::ok() <- com.mbed.coap.packet.CoapResponse is used as a type parameter or type variable bound on method java.util.concurrent.CompletableFuture<com.mbed.coap.packet.CoapResponse> org.eclipse.leshan.transport.javacoap.resource.LwM2mCoapResource::handleInvalidRequest(com.mbed.coap.packet.CoapRequest, java.lang.String, java.lang.Throwable) (method java.util.concurrent.CompletableFuture<com.mbed.coap.packet.CoapResponse> org.eclipse.leshan.transport.javacoap.resource.LwM2mCoapResource::handleInvalidRequest(com.mbed.coap.packet.CoapRequest, java.lang.String, java.lang.Throwable) is part of the API)",
  "package": "com.mbed.coap.packet",
  "classQualifiedName": "com.mbed.coap.packet.RawOption",
  "elementKind": "class",
  "newArchive": "io.github.open-coap:coap-core:jar:6.21.0",
  "newArchiveRole": "supplementary",
},
```

`nonPublicPartOfAPI` is described [here](https://revapi.org/revapi-java/0.28.1/differences.html#java.class.nonPublicPartOfAPI).

I copy/paste the `exampleUseChainInNewApi` here because this is the most important part to understand the issue : 
> "com.mbed.coap.packet.RawOption is used as a type parameter or type variable bound on method java.util.List<com.mbed.coap.packet.RawOption> com.mbed.coap.packet.HeaderOptions::getRawOptions() <- com.mbed.coap.packet.HeaderOptions is used as a type parameter or type variable bound on method com.mbed.coap.packet.CoapOptionsBuilder com.mbed.coap.packet.CoapOptionsBuilder::ifNull(java.util.function.Function<com.mbed.coap.packet.HeaderOptions, java.lang.Object>, java.util.function.Consumer<com.mbed.coap.packet.CoapOptionsBuilder>) <- com.mbed.coap.packet.CoapOptionsBuilder is used as a type parameter or type variable bound on method com.mbed.coap.packet.CoapResponse.Builder com.mbed.coap.packet.CoapResponse.Builder::options(java.util.function.Consumer<com.mbed.coap.packet.CoapOptionsBuilder>) <- com.mbed.coap.packet.CoapResponse.Builder is returned from method com.mbed.coap.packet.CoapResponse.Builder com.mbed.coap.packet.CoapResponse::ok() <- com.mbed.coap.packet.CoapResponse is used as a type parameter or type variable bound on method java.util.concurrent.CompletableFuture<com.mbed.coap.packet.CoapResponse> org.eclipse.leshan.transport.javacoap.resource.LwM2mCoapResource::handleInvalidRequest(com.mbed.coap.packet.CoapRequest, java.lang.String, java.lang.Throwable) (method java.util.concurrent.CompletableFuture<com.mbed.coap.packet.CoapResponse> org.eclipse.leshan.transport.javacoap.resource.LwM2mCoapResource::handleInvalidRequest(com.mbed.coap.packet.CoapRequest, java.lang.String, java.lang.Throwable) is part of the API)"

**Solution ?** 

I think   `RawOption` should be **protected** instead of **package** ? 

(issue found with 6.21.0)

**Comment by szysas** [comment]
Well, top level class cannot be protected, only option is to make it public, for which I don't see why not.
