### ISSUE TITLE
Is this `transient` really necessary in  `RequestMatcher`? 

### ISSUE THREAD

**Issue by sbernard31** [open-coap/java-coap#88]
Working on https://github.com/eclipse-leshan/leshan/issues/1504#issuecomment-2275053190, we found a field with `transient` modifier ? https://github.com/open-coap/java-coap/blob/ef8b0e2542a0f7533a005cb0f2238dcbc6b69fc9/coap-core/src/main/java/com/mbed/coap/server/RouterService.java#L154

Is it wanted ?

**Comment by szysas** [comment]
Well, not really but it is used by `EqualsVerifier` tool to skip fields when testing `equals` and `hashCode` methods (AFAIK).

**Comment by sbernard31** [comment]
I just remember that I already asked this question more than 1 year ago :man_facepalming: 

See https://github.com/open-coap/java-coap/issues/52#issuecomment-1532688800

Sorry for noise. :pray:

**Comment by szysas** [comment]
Ohh, you have a good memory, I did not remember that ;)
